baseurl = "/"
languageCode = "en-us"
title = "Science in Progress"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "iTunes"
    url = "https://itunes.apple.com/us/podcast/science-in-progress/id1360406328"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rob_c_ornelas"

[params]
    description = "A podcase featuring discussions with early career ecologists"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "SIP_Logo_smaller.jpg"
    width = 50
    height = 50
    alt = "Logo"

